### ISSUE TITLE
What's the alpha in AG2E function?

### ISSUE THREAD

**Issue by chamwen** [wanglichenxj/AG2E_Multi_Label#1]
% Initialize weighted distance
distX_initial =  L2_distance_1(PX,PX);
...
**alpha = mean(rr);**

**Comment by wanglichenxj** [comment]
Thanks for your question. We were inspired by the code from the work: Multi-view Clustering and Semi-supervised Classification with Adaptive Neighbours. AAAI'17 for the equation optimization procedure. We consider the alpha as a data normalization procedure which balances the scale for optimizations.

**Comment by chamwen** [comment]
@wanglichenxj Thanks a lot!
